### ISSUE TITLE
REQUESTING TO HELP 

### ISSUE THREAD

**Issue by Gani-23** [MKC-MKC/Acer_Nitro_5_AN515-54-51NJ-EFI-OpenCore#6]
hey mate can you please help me with creation of opencore/clover EFI for VENTURA
my contact : [saiganesh7989@gmail.com](mailto:saiganesh7989@gmail.com)

my configurations are

Device model name: ACER NITRO 515-52
Processor: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz 2.30 GHz
Installed RAM: 8.00 GB (7.84 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

REALTEK ALC 255 DRIVERS

500 GIGS -SSD NVME.2
1 TB HDD - TOSHIBA
Nvidia GE force GTX - 1050

**Comment by MKC-MKC** [comment]
answered
